---
version: '3'
services:
    vault-dev-server:
        image: vault:1.3.1
        ports:
            - "8200:8200"
        cap_add:
            - IPC_LOCK
        environment:
            - VAULT_DEV_ROOT_TOKEN_ID=a-silly-token-for-dev
            - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
            - VAULT_ADDR=http://0.0.0.0:8200
